#include <functional>
#include <iterator>
#include <libdialect/ortho.h>
#include <libvpsc/rectangle.h>
#include <map>
#include <memory>
#include <set>
#include <sstream> // __str__
#include <utility>

#include <functional>
#include <pybind11/pybind11.h>
#include <string>

#ifndef BINDER_PYBIND11_TYPE_CASTER
	#define BINDER_PYBIND11_TYPE_CASTER
	PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>)
	PYBIND11_DECLARE_HOLDER_TYPE(T, T*)
	PYBIND11_MAKE_OPAQUE(std::shared_ptr<void>)
#endif

void bind_std_map_2(std::function< pybind11::module &(std::string const &namespace_) > &M)
{
	{ // std::map file:map line:898
		pybind11::class_<std::map<unsigned int,unsigned int>, std::shared_ptr<std::map<unsigned int,unsigned int>>> cl(M("std"), "map_unsigned_int_unsigned_int_t", "");
		cl.def( pybind11::init( [](){ return new std::map<unsigned int,unsigned int>(); } ) );
		cl.def( pybind11::init<const struct std::less<unsigned int> &>(), pybind11::arg("__comp") );

		cl.def( pybind11::init<const struct std::less<unsigned int> &, const class std::allocator<struct std::pair<const unsigned int, unsigned int> > &>(), pybind11::arg("__comp"), pybind11::arg("__a") );

		cl.def( pybind11::init( [](std::map<unsigned int,unsigned int> const &o){ return new std::map<unsigned int,unsigned int>(o); } ) );
		cl.def( pybind11::init<const class std::allocator<struct std::pair<const unsigned int, unsigned int> > &>(), pybind11::arg("__a") );

		cl.def( pybind11::init<const class std::map<unsigned int, unsigned int, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, unsigned int> > > &, const class std::allocator<struct std::pair<const unsigned int, unsigned int> > &>(), pybind11::arg("__m"), pybind11::arg("__a") );

		cl.def("assign", (class std::map<unsigned int, unsigned int, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, unsigned int> > > & (std::map<unsigned int,unsigned int>::*)(const class std::map<unsigned int, unsigned int, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, unsigned int> > > &)) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::operator=, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::operator=(const class std::map<unsigned int, unsigned int, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, unsigned int> > > &) --> class std::map<unsigned int, unsigned int, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, unsigned int> > > &", pybind11::return_value_policy::automatic, pybind11::arg("__m"));
		cl.def("empty", (bool (std::map<unsigned int,unsigned int>::*)() const) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::empty, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::empty() const --> bool");
		cl.def("size", (unsigned long (std::map<unsigned int,unsigned int>::*)() const) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::size, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::size() const --> unsigned long");
		cl.def("max_size", (unsigned long (std::map<unsigned int,unsigned int>::*)() const) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::max_size, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::max_size() const --> unsigned long");
		cl.def("__getitem__", (unsigned int & (std::map<unsigned int,unsigned int>::*)(const unsigned int &)) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::operator[], "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::operator[](const unsigned int &) --> unsigned int &", pybind11::return_value_policy::automatic, pybind11::arg("__k"));
		cl.def("at", (unsigned int & (std::map<unsigned int,unsigned int>::*)(const unsigned int &)) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::at, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::at(const unsigned int &) --> unsigned int &", pybind11::return_value_policy::automatic, pybind11::arg("__k"));
		cl.def("get_allocator", (class std::allocator<struct std::pair<const unsigned int, unsigned int> > (std::map<unsigned int,unsigned int>::*)() const) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::get_allocator, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::get_allocator() const --> class std::allocator<struct std::pair<const unsigned int, unsigned int> >");
		cl.def("key_comp", (struct std::less<unsigned int> (std::map<unsigned int,unsigned int>::*)() const) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::key_comp, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::key_comp() const --> struct std::less<unsigned int>");
		cl.def("insert", (struct std::pair<class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, unsigned int>, class std::__tree_node<struct std::__value_type<unsigned int, unsigned int>, void *> *, long> >, bool> (std::map<unsigned int,unsigned int>::*)(const struct std::pair<const unsigned int, unsigned int> &)) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::insert, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::insert(const struct std::pair<const unsigned int, unsigned int> &) --> struct std::pair<class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, unsigned int>, class std::__tree_node<struct std::__value_type<unsigned int, unsigned int>, void *> *, long> >, bool>", pybind11::arg("__v"));
		cl.def("erase", (unsigned long (std::map<unsigned int,unsigned int>::*)(const unsigned int &)) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::erase, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::erase(const unsigned int &) --> unsigned long", pybind11::arg("__k"));
		cl.def("clear", (void (std::map<unsigned int,unsigned int>::*)()) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::clear, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::clear() --> void");
		cl.def("swap", (void (std::map<unsigned int,unsigned int>::*)(class std::map<unsigned int, unsigned int, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, unsigned int> > > &)) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::swap, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::swap(class std::map<unsigned int, unsigned int, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, unsigned int> > > &) --> void", pybind11::arg("__m"));
		cl.def("count", (unsigned long (std::map<unsigned int,unsigned int>::*)(const unsigned int &) const) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::count, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::count(const unsigned int &) const --> unsigned long", pybind11::arg("__k"));
		cl.def("equal_range", (struct std::pair<class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, unsigned int>, class std::__tree_node<struct std::__value_type<unsigned int, unsigned int>, void *> *, long> >, class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, unsigned int>, class std::__tree_node<struct std::__value_type<unsigned int, unsigned int>, void *> *, long> > > (std::map<unsigned int,unsigned int>::*)(const unsigned int &)) &std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::equal_range, "C++: std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >::equal_range(const unsigned int &) --> struct std::pair<class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, unsigned int>, class std::__tree_node<struct std::__value_type<unsigned int, unsigned int>, void *> *, long> >, class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, unsigned int>, class std::__tree_node<struct std::__value_type<unsigned int, unsigned int>, void *> *, long> > >", pybind11::arg("__k"));
	}
	{ // std::map file:map line:898
		pybind11::class_<std::map<unsigned int,std::set<unsigned int>>, std::shared_ptr<std::map<unsigned int,std::set<unsigned int>>>> cl(M("std"), "map_unsigned_int_std_set_unsigned_int_t", "");
		cl.def( pybind11::init( [](){ return new std::map<unsigned int,std::set<unsigned int>>(); } ) );
		cl.def( pybind11::init<const struct std::less<unsigned int> &>(), pybind11::arg("__comp") );

		cl.def( pybind11::init<const struct std::less<unsigned int> &, const class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > &>(), pybind11::arg("__comp"), pybind11::arg("__a") );

		cl.def( pybind11::init( [](std::map<unsigned int,std::set<unsigned int>> const &o){ return new std::map<unsigned int,std::set<unsigned int>>(o); } ) );
		cl.def( pybind11::init<const class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > &>(), pybind11::arg("__a") );

		cl.def( pybind11::init<const class std::map<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> >, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > > &, const class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > &>(), pybind11::arg("__m"), pybind11::arg("__a") );

		cl.def("assign", (class std::map<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> >, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > > & (std::map<unsigned int,std::set<unsigned int>>::*)(const class std::map<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> >, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > > &)) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::operator=, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::operator=(const class std::map<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> >, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > > &) --> class std::map<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> >, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > > &", pybind11::return_value_policy::automatic, pybind11::arg("__m"));
		cl.def("empty", (bool (std::map<unsigned int,std::set<unsigned int>>::*)() const) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::empty, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::empty() const --> bool");
		cl.def("size", (unsigned long (std::map<unsigned int,std::set<unsigned int>>::*)() const) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::size, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::size() const --> unsigned long");
		cl.def("max_size", (unsigned long (std::map<unsigned int,std::set<unsigned int>>::*)() const) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::max_size, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::max_size() const --> unsigned long");
		cl.def("__getitem__", (class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > & (std::map<unsigned int,std::set<unsigned int>>::*)(const unsigned int &)) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::operator[], "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::operator[](const unsigned int &) --> class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > &", pybind11::return_value_policy::automatic, pybind11::arg("__k"));
		cl.def("at", (class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > & (std::map<unsigned int,std::set<unsigned int>>::*)(const unsigned int &)) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::at, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::at(const unsigned int &) --> class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > &", pybind11::return_value_policy::automatic, pybind11::arg("__k"));
		cl.def("get_allocator", (class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > (std::map<unsigned int,std::set<unsigned int>>::*)() const) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::get_allocator, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::get_allocator() const --> class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > >");
		cl.def("key_comp", (struct std::less<unsigned int> (std::map<unsigned int,std::set<unsigned int>>::*)() const) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::key_comp, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::key_comp() const --> struct std::less<unsigned int>");
		cl.def("insert", (struct std::pair<class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, class std::__tree_node<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, void *> *, long> >, bool> (std::map<unsigned int,std::set<unsigned int>>::*)(const struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > &)) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::insert, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::insert(const struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > &) --> struct std::pair<class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, class std::__tree_node<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, void *> *, long> >, bool>", pybind11::arg("__v"));
		cl.def("erase", (unsigned long (std::map<unsigned int,std::set<unsigned int>>::*)(const unsigned int &)) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::erase, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::erase(const unsigned int &) --> unsigned long", pybind11::arg("__k"));
		cl.def("clear", (void (std::map<unsigned int,std::set<unsigned int>>::*)()) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::clear, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::clear() --> void");
		cl.def("swap", (void (std::map<unsigned int,std::set<unsigned int>>::*)(class std::map<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> >, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > > &)) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::swap, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::swap(class std::map<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> >, struct std::less<unsigned int>, class std::allocator<struct std::pair<const unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > > > > &) --> void", pybind11::arg("__m"));
		cl.def("count", (unsigned long (std::map<unsigned int,std::set<unsigned int>>::*)(const unsigned int &) const) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::count, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::count(const unsigned int &) const --> unsigned long", pybind11::arg("__k"));
		cl.def("equal_range", (struct std::pair<class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, class std::__tree_node<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, void *> *, long> >, class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, class std::__tree_node<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, void *> *, long> > > (std::map<unsigned int,std::set<unsigned int>>::*)(const unsigned int &)) &std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::equal_range, "C++: std::map<unsigned int, std::set<unsigned int>, std::less<unsigned int>, std::allocator<std::pair<const unsigned int, std::set<unsigned int> > > >::equal_range(const unsigned int &) --> struct std::pair<class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, class std::__tree_node<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, void *> *, long> >, class std::__map_iterator<class std::__tree_iterator<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, class std::__tree_node<struct std::__value_type<unsigned int, class std::set<unsigned int, struct std::less<unsigned int>, class std::allocator<unsigned int> > >, void *> *, long> > >", pybind11::arg("__k"));
	}
}
